# -*- coding: utf-8 -*-
"""history_and_development

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBlLQKoi7DO1ii6rD16Y_iF7I8VUngHa

## Name Extraction Exercise

Simple script to perform name extraction from a list of names.
"""

list_of_possible_names = [
    'Liam', 'Noah', "Oliver", "William", "Elijah",
    "James", "Benjamin", "Lucas", "Mason", "Ethan",
    "Alexander"
]
list_of_possible_names = [l.lower() for l in list_of_possible_names]

def parse_name(sentence):
    for word in sentence.split():
        if word.lower() in list_of_possible_names:
            return word


sentence = input("Enter your name:")
print()
name = parse_name(sentence)
if name is not None:
    print(f"Greetings {name}")
else:
    print("No name provided. Please try again.")

